package utils;
import java.util.Random;

public class Utility {
    public int roll(int max) {
        Random r = new Random();
        return r.nextInt(max) + 1;
    }
    
    public enum ItemWeight {LIGHT, MEDIUM, HEAVY}
    
    public enum TileName {AWFULVALLEY, BADVALLEY, BORDERLAND, CAVERN, CAVES, CLIFF, CRAG, CURSTVALLEY,
    	DARKVALLEY, DEEPWOODS, EVILVALLEY, HIGHPASS, LEDGES, LINDENWOODS, MAPLEWOODS, MOUNTAIN, NUTWOODS,
    	OAKWOODS, PINEWOODS, RUINS
    }
    
    public enum WeaponName {MEDIUM_BOW, LIGHT_BOW, CROSSBOW, SPEAR, STAFF, GREAT_SWORD, BANE_SWORD, BROADSWORD,
    	DEVIL_SWORD, TRUESTEEL_SWORD, MORNING_STAR, GREAT_AXE, THRUSTING_SWORD, LIVING_SWORD, SHORT_SWORD,
    	AXE, MACE, DAGGER, TOOTH_AND_CLAW}
    
    public enum ArmorName {SUIT_OF_ARMOR, BREASTPLATE, HELMET, SHIELF, TREMENDOUS_ARMOR, SILVER_BREASTPLATE,
    	GOLD_HELMET, JADE_SHIELD}
    
    public enum CharacterName {AMAZON, BERSERKER, BLACK_KNIGHT, CAPTAIN, DRUID, DWARF, ELF, MAGICIAN, PILGRIM, SORCEROR,
    	SWORDSMAN, WHITE_KNIGHT, WITCH, WITCH_KING, WIZARD, WOODS_GIRL}
    
    public enum HorseName {PONY, WORKHORSE, WARHORSE}
    
    public enum MonsterName {TREMENDOUS_FLYING_DRAGON, T_FLYING_DRAGON_HEAD, TREMENDOUS_DRAGON, T_DRAGON_HEAD,
    	GIANT, GIANT_CLUB, WINGED_DEMON, DEMON, TREMENDOUS_TROLL, OCTOPUS, TREMENDOUS_SERPENT, TREMENDOUS_SPIDER,
    	HEAVY_FLYING_DRAGON, HEAVY_DRAGON, HEAVY_TROLL, HEAVY_SERPENT, GIANT_BAT, HEAVY_SPIDER, IMP, GOBLIN_WITH_SPEAR,
    	GOBLIN_WITH_GREATSWORD, GOBLIN_WITH_AXE, VIPER, GHOST, OGRE, WOLF}
    
    public enum NativeName {KNIGHT, GREAT_SWORDSMAN, GREAT_AXEMAN, PIKEMAN, SHORT_SWORDSMAN, CROSSBOWMAN, LANCER,
    	RAIDER, ARCHER, SWORDSMAN, ASSASSIN}
    
    public enum TreasureType{GOLD, GLOVE, BOOTS}
    
    //May need to become part of treasure, we shall see.
    public enum GloveName {DEFT_GLOVES, GLOVES_OF_STRENGTH, HANDY_GLOVES, POWER_GAUNTLETS}
	public enum BootName {ELVEN_SLIPPERS, POWER_BOOTS, QUICK_BOOTS, LEAGUE_BOOTS, SHOES_OF_STEALTH}
    
}